apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: internal-kubectl-commands-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: internal-kubectl-commands-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: internal-kubectl-commands-clusterrole
  apiGroup: rbac.authorization.k8s.io