apiVersion: v1
kind: ConfigMap
metadata:
  name: scale-to-zero
  namespace: kube-system
data:
  deployments.config: |
    cat <<EOF > deployments.config
    bx-cnsr-salida-ruta-records,prod-ns-salida-ruta,3,20
    EOF   